version: '3'
services:
    zed-ros2:
        privileged: true
        image: "humble_zed_bdy__track:latest"
        ipc: host
        pid: host
        network_mode: host
        environment:
            - PULSE_SERVER=tcp:host.docker.internal:4713
            - ROS_DOMAIN_ID=22
            - DISPLAY=$DISPLAY
            - FASTRTPS_DEFAULT_PROFILES_FILE=/profile/fastrtps_default_profiles.xml
        volumes:
            - /tmp/.X11-unix/:/tmp/.X11-unix
            - ./profile:/profile
            - ./zed_launch.bash:/tmp/zed_launch.bash 
            - /dev:/dev
            - /usr/local/zed/resources:/usr/local/zed/resources
        tty: true
        #command: /tmp/zed_launch.bash
        deploy: 
         resources:
          reservations:
           devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
